from typing import Any

API_SCHEMA_VERSION: int


class PyGuandanGame:
    def __init__(self, seed: int, level: int, human_seat: int) -> None: ...
    @property
    def current_player(self) -> int | None: ...
    @property
    def terminal(self) -> bool: ...
    def state(self, observer: int) -> dict[str, Any]: ...
    def step_action(self, actor: int, action_index: int) -> dict[str, Any]: ...
    def play_cards(self, actor: int, card_ids: list[int] | None) -> dict[str, Any]: ...

