"""Static types for the PyO3 extension module."""

from typing import Final

import numpy as np
from numpy.typing import NDArray

from .batch_types import BatchObservation, BatchStepResult, PackedActions
from .env_types import (
    Action,
    ExactSolveResult,
    Observation,
    RuleConfig,
    StepResult,
    VersionedRuleConfig,
)

API_SCHEMA_VERSION: Final[int]
BATCH_SCHEMA_VERSION: Final[int]
SHUFFLE_ALGORITHM: Final[str]

def parse_rule_config(yaml_text: str) -> RuleConfig: ...
def parse_versioned_rule_config(yaml_text: str) -> VersionedRuleConfig: ...
def rule_config_hash(yaml_text: str) -> str: ...
def generate_lead_actions(rank_counts: list[int], rule_config: RuleConfig) -> list[Action]: ...
def minimum_play_groups(
    rank_count_batch: list[list[int]], rule_config: RuleConfig, count_cap: int
) -> list[dict[str, int]]: ...
def solve_endgame(
    serialized_state: bytes,
    rule_config: RuleConfig,
    max_total_cards: int,
    max_nodes: int,
) -> ExactSolveResult: ...

class PyDdzEnv:
    """One deterministic Rust-backed post-bid environment."""

    def __init__(self) -> None: ...
    @property
    def seed(self) -> int | None: ...
    @property
    def is_initialized(self) -> bool: ...
    @property
    def current_player(self) -> int: ...
    @property
    def terminal(self) -> bool: ...
    def reset(self, seed: int, rule_config: RuleConfig) -> Observation: ...
    def reset_complete_deal(
        self,
        hands: list[list[int]],
        bottom_cards: list[int],
        first_bidder: int,
        rule_config: RuleConfig,
    ) -> Observation: ...
    def restore(self, serialized_state: bytes, rule_config: RuleConfig) -> Observation: ...
    def restore_with_hidden_sample(
        self,
        serialized_state: bytes,
        rule_config: RuleConfig,
        observer: int,
        assignment_a: list[int],
    ) -> Observation: ...
    def legal_actions(self) -> list[Action]: ...
    def step(self, action: Action) -> StepResult: ...
    def observe(self, player: int) -> Observation: ...
    def serialize(self) -> bytes: ...

class PyBatchDdzEnv:
    """Multiple Rust environments using contiguous NumPy transport buffers."""

    def __init__(self, rule_config: RuleConfig) -> None: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def is_initialized(self) -> bool: ...
    @property
    def all_terminal(self) -> bool: ...
    def reset(self, seeds: NDArray[np.uint64]) -> BatchObservation: ...
    def observe_packed(self) -> BatchObservation: ...
    def legal_actions_packed(self) -> PackedActions: ...
    def step_packed(self, action_indices: NDArray[np.int64]) -> BatchStepResult: ...
